name: chemo_monitor_app
description: AI-Integrated Chemotherapy Patient Monitoring App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.1
  firebase_storage: ^11.6.0
    
  # UI & Design
  animations: ^2.0.8
  font_awesome_flutter: ^10.7.0
  line_icons: ^2.0.3
  shimmer: ^3.0.0
  url_launcher: ^6.2.2
  photo_view: ^0.14.0
  
  # Charts & Visualization
  fl_chart: ^0.66.2
    
  # File Handling
  image_picker: ^1.0.7
  cloudinary_public: ^0.21.0
    
  
  # HTTP & APIs
  http: ^1.2.0
    
  # Utilities
  intl: ^0.19.0
  crypto: ^3.0.3
  uuid: ^4.3.3
    
  # ML
  tflite_flutter: ^0.11.0
    
  # Environment
  flutter_dotenv: ^5.1.0
    
  # Markdown for chatbot
  flutter_markdown: ^0.6.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_svg: ^2.0.10
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
    
  assets:
    - .env
    - assets/images/
    - assets/animations/
    - assets/fonts/
    - assets/models/model.tflite
    - assets/images/chemo_care.png
    - assets/images/app_logo.png
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  min_sdk_android: 21